package com.atguigu.springcloud.entities.coreVo.AbstractVo;
// default package

import java.util.Date;


/**
 * AbstractPlyAcctinfoVO generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAcctinfoVO implements java.io.Serializable {


    // Fields    

    private String CAppNo;
    private String CPlyNo;
    private Long NEdrPrjNo;
    private String CEdrNo;
    private String CAcctNme;
    private String CAcctNo;
    private String CBankRelCde;
    private String CBankPro;
    private String CBankArea;
    private String CBankCde;
    private String CCrtCde;
    private Date TCrtTm;
    private String CUpdCde;
    private Date TUpdTm;

    private String CBankCounty;
    private String CBankRelTyp;
    private String CBankCnaps;
    private String CBankAddr;
    private String CPubPri;
    private String CTransMrk;
    private Date TTransTm;

    // Constructors

    public String getCTransMrk() {
        return CTransMrk;
    }

    public void setCTransMrk(String transMrk) {
        CTransMrk = transMrk;
    }

    public Date getTTransTm() {
        return TTransTm;
    }

    public void setTTransTm(Date transTm) {
        TTransTm = transTm;
    }

    public String getCBankRelTyp() {
        return CBankRelTyp;
    }

    public void setCBankRelTyp(String bankRelTyp) {
        CBankRelTyp = bankRelTyp;
    }

    public String getCBankCnaps() {
        return CBankCnaps;
    }

    public void setCBankCnaps(String bankCnaps) {
        CBankCnaps = bankCnaps;
    }

    public String getCBankAddr() {
        return CBankAddr;
    }

    public void setCBankAddr(String bankAddr) {
        CBankAddr = bankAddr;
    }

    public String getCPubPri() {
        return CPubPri;
    }

    public void setCPubPri(String pubPri) {
        CPubPri = pubPri;
    }

    public String getCBankCounty() {
        return CBankCounty;
    }

    public void setCBankCounty(String bankCounty) {
        CBankCounty = bankCounty;
    }

    /** default constructor */
    public AbstractAcctinfoVO() {
    }
    // Property accessors

    public String getCAppNo() {
        return this.CAppNo;
    }

    public void setCAppNo(String CAppNo) {
        this.CAppNo = CAppNo;
    }

    public String getCPlyNo() {
        return this.CPlyNo;
    }

    public void setCPlyNo(String CPlyNo) {
        this.CPlyNo = CPlyNo;
    }

    public Long getNEdrPrjNo() {
        return this.NEdrPrjNo;
    }

    public void setNEdrPrjNo(Long NEdrPrjNo) {
        this.NEdrPrjNo = NEdrPrjNo;
    }

    public String getCEdrNo() {
        return this.CEdrNo;
    }

    public void setCEdrNo(String CEdrNo) {
        this.CEdrNo = CEdrNo;
    }

    public String getCAcctNme() {
        return this.CAcctNme;
    }

    public void setCAcctNme(String CAcctNme) {
        this.CAcctNme = CAcctNme;
    }

    public String getCAcctNo() {
        return this.CAcctNo;
    }

    public void setCAcctNo(String CAcctNo) {
        this.CAcctNo = CAcctNo;
    }

    public String getCBankRelCde() {
        return this.CBankRelCde;
    }

    public void setCBankRelCde(String CBankRelCde) {
        this.CBankRelCde = CBankRelCde;
    }

    public String getCBankPro() {
        return this.CBankPro;
    }

    public void setCBankPro(String CBankPro) {
        this.CBankPro = CBankPro;
    }

    public String getCBankArea() {
        return this.CBankArea;
    }

    public void setCBankArea(String CBankArea) {
        this.CBankArea = CBankArea;
    }

    public String getCBankCde() {
        return this.CBankCde;
    }

    public void setCBankCde(String CBankCde) {
        this.CBankCde = CBankCde;
    }

    public String getCCrtCde() {
        return this.CCrtCde;
    }

    public void setCCrtCde(String CCrtCde) {
        this.CCrtCde = CCrtCde;
    }

    public Date getTCrtTm() {
        return this.TCrtTm;
    }

    public void setTCrtTm(Date TCrtTm) {
        this.TCrtTm = TCrtTm;
    }

    public String getCUpdCde() {
        return this.CUpdCde;
    }

    public void setCUpdCde(String CUpdCde) {
        this.CUpdCde = CUpdCde;
    }

    public Date getTUpdTm() {
        return this.TUpdTm;
    }

    public void setTUpdTm(Date TUpdTm) {
        this.TUpdTm = TUpdTm;
    }


}