package com.atguigu.springcloud.entities.coreVo;
// default package
// Generated by MyEclipse Persistence Tools


import com.atguigu.springcloud.entities.coreVo.AbstractVo.AbstractAcctinfoVO;

/**
 * PlyAcctinfoVO generated by MyEclipse Persistence Tools
 */
public class PlyAcctinfoVO extends AbstractAcctinfoVO implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 8210449783339325678L;

	/** default constructor */
    public PlyAcctinfoVO() {
    }
    
    private String CLatestMrk;

	public String getCLatestMrk() {
		return CLatestMrk;
	}

	public void setCLatestMrk(String latestMrk) {
		CLatestMrk = latestMrk;
	}
    
}
