server:
  port: 9527
spring:
  application:
    name: beauty-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/payment/nacos/{id} #断言,路径相匹配的进行路由

